version: "3.5"

services:

  jbrowse2:
    image: jbrowse2:${JBROWSE2_TAG:-latest}

    volumes:
      - type: bind
        source: ${MACHINE_FILES_DIR:-/var/www/Common/apiSiteFilesMirror/webServices}
        target: ${SERVICE_FILES_MOUNT:-/data}
        read_only: true

    ports:
      - "${JBROWSE2_SERVER_PORT:-8080}:${JBROWSE2_SERVER_PORT:-8080}"

    environment:

      # port providing the service
      JBROWSE2_SERVER_PORT: ${JBROWSE2_SERVER_PORT:-8080}

      # location of data files
      SERVICE_FILES_MOUNT: ${SERVICE_FILES_MOUNT:-/data}

    labels:
    - "com.centurylinklabs.watchtower.enable=${JBROWSE2_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.loadbalancer.server.port=${JBROWSE2_SERVER_PORT:-8080}"
    - "traefik.http.routers.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.rule=Host(`${TRAEFIK_JBROWSE2_HOST:-jbrowse2-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.tls=${USE_TRAEFIK_SSL:-true}"
    - "traefik.http.routers.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

    networks:
      - internal
      - traefik

networks:
  internal:
    external: false
  traefik:
    external: true
