version: "3.5"

services:

  jbrowse2:
    image: ${JBROWSE2_IMAGE_NAME:-veupathdb/jbrowse2}:${JBROWSE2_TAG:-latest}

    networks:
      internal:
      external:
      monitoring-ext:
      traefik:

    volumes:
      - type: bind
        source: ${MACHINE_FILES_DIR:-/var/www/Common/apiSiteFilesMirror/webServices}
        target: ${SERVICE_FILES_MOUNT:-/data}
        read_only: true

    environment:

      # port providing the service
      JBROWSE2_SERVER_PORT: ${JBROWSE2_SERVER_PORT:-8080}

      # location of data files
      SERVICE_FILES_MOUNT: ${SERVICE_FILES_MOUNT:-/data}

      # how often to check for config.json modification (will refresh on mod)
      CONFIG_JSON_CHECK_INTERVAL_SECS: ${CONFIG_JSON_CHECK_INTERVAL_SECS:-30}

    labels:
      - "com.centurylinklabs.watchtower.enable=${JBROWSE2_WATCHTOWER:-false}"
      - "traefik.http.services.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.loadbalancer.server.port=${JBROWSE2_SERVER_PORT:-8080}"
      - "traefik.http.routers.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.rule=Host(`${TRAEFIK_JBROWSE2_HOST:-jbrowse2-dev.local.apidb.org}`)"
      - "traefik.http.routers.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.tls=${USE_TRAEFIK_SSL:-true}"
      - "traefik.http.routers.${TRAEFIK_JBROWSE2_ROUTER:-jbrowse2-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
      - "traefik.docker.network=traefik"

networks:
  # external network used for containers that need to reach outside
  external:
  traefik:
    external: true
  internal:
    internal: true
  monitoring-ext:
    external: true
